var files = [
//    "app.backend.js",
//    "app.box.gc.js",
    "app.box.js",
    "app.bugfix.call.js",
    "app.fetch.call.js",
    "app.fetch.mail-sx.js",
    "app.fetch.mail.js",
    "app.fetch.other.js",
    "app.fetch.reminder.js",
    "app.fetch.schedule.js",
    "app.fetch.unstable.js",
    "app.hook.js",
    "app.js",
//    "app.move.binding.js",
//    "app.plugin.init.js",
//    "app.statistic.js",
//    "app.team.init.js",
    "server/api/activity.js",
    "server/api/apply.js",
    "server/api/authorization.js",
    "server/api/base.js",
    "server/api/calendar.js",
    "server/api/call.js",
    "server/api/channel.js",
    "server/api/comment.js",
    "server/api/department.js",
    "server/api/drive.js",
    "server/api/entity.js",
    "server/api/favorite.js",
    "server/api/feedback.js",
    "server/api/follow.js",
    "server/api/index.js",
    "server/api/integration.js",
    "server/api/like.js",
    "server/api/message.js",
    "server/api/mission.js",
    "server/api/mobileApi/call.js",
    "server/api/mobileApi/channel.js",
    "server/api/mobileApi/entity.js",
    "server/api/mobileApi/index.js",
    "server/api/mobileApi/team.js",
    "server/api/mobileApi/user.js",
    "server/api/mobileApi/version.js",
    "server/api/pinned.js",
    "server/api/preference.js",
    "server/api/reply.js",
    "server/api/report.js",
    "server/api/resource.js",
    "server/api/schedule.js",
    "server/api/service.js",
    "server/api/session.js",
    "server/api/sharedlink.js",
    "server/api/sms.js",
    "server/api/tag.js",
    "server/api/team.js",
    "server/api/user.js",
    "server/api/work_report.js",
//    "server/backend/apnsNotify.js",
//    "server/backend/fetch_url_info.js",
//    "server/backend/general.js",
//    "server/backend/index.js",
//    "server/backend/outgoing.js",
//    "server/backend/reply.js",
//    "server/backend/sqs.js",
//    "server/backend/sqs_aliyun_handler.js",
//    "server/backend/sqs_amazon_handler.js",
//    "server/backend/tuling.js",
//    "server/backend/unfurling.js",
//    "server/backend/weixin.js",
//    "server/backend/xiaote_reply.js",
    "server/box/authentication.js",
    "server/box/controllers.js",
    "server/box/middlewares.js",
    "server/box/plugins/context_entity_mapper.js",
    "server/box/plugins/exiftool.js",
    "server/box/plugins/feedback.js",
    "server/box/plugins/ffmpeg.js",
    "server/box/plugins/ffprobe.js",
    "server/box/plugins/gifsicle.js",
    "server/box/plugins/immagick.js",
    "server/box/plugins/index.js",
    "server/box/plugins/lc_attachment.js",
    "server/box/plugins/lc_drive.js",
    "server/box/plugins/lc_team_logo.js",
    "server/box/plugins/lib/growing-file.js",
    "server/box/plugins/lib/packaging.js",
    "server/box/plugins/manager.js",
    "server/box/plugins/resize.js",
    "server/box/route.js",
    "server/box/status.js",
    "server/box/storages/proxy/box.js",
    "server/box/storages/proxy/general.js",
    "server/box/storages/proxy/index.js",
    "server/box/storages/proxy/manager.js",
    "server/box/storages/s3/index.js",
    "server/box/storages/s3/manager.js",
    "server/box/storages/s3/multipart.js",
    "server/box/storages/s3/utils.js",
    "server/config/development-with-local-box.js",
    "server/config/development.js",
    "server/config/index.js",
    "server/config/localtest.js",
    "server/config/production.confidential.js",
    "server/config/production.js",
    "server/config/role/development/backend.js",
    "server/config/role/development/box.js",
    "server/config/role/development/general.js",
    "server/config/role/development/localtest.js",
    "server/config/role/development/web.js",
    "server/config/role/production/backend.js",
    "server/config/role/production/box.js",
    "server/config/role/production/fetch.js",
    "server/config/role/production/hook.js",
    "server/config/role/production/web.js",
    "server/config/scripts.js",
    "server/config/test.js",
    "server/controller/home.js",
    "server/controller/index.js",
    "server/controller/mobile.js",
    "server/controller/share.js",
    "server/core/auth.js",
    "server/core/automation.js",
    "server/core/constant.js",
    "server/core/converter.js",
    "server/core/index.js",
//    "server/core/logger.js",
    "server/core/mailer.js",
    "server/core/redis.js",
    "server/core/status.js",
    "server/core/util.js",
    "server/core/utils/argv-parser.js",
    "server/core/utils/auditor.js",
    "server/core/utils/index.js",
    "server/core/utils/suicide.js",
    "server/core/validator.js",
//    "server/data/activity.js",
//    "server/data/apply.js",
//    "server/data/authorization.js",
//    "server/data/base.js",
//    "server/data/calendar/calendar.event.instance.js",
//    "server/data/calendar/calendar.event.js",
//    "server/data/calendar/calendar.js",
//    "server/data/call_addition.js",
//    "server/data/call_duration.js",
//    "server/data/call_record.js",
//    "server/data/call_status.js",
//    "server/data/channel.js",
//    "server/data/client_number.js",
//    "server/data/comment.js",
//    "server/data/department.js",
//    "server/data/domain.js",
//    "server/data/drive.js",
//    "server/data/elasticsearch/entities_mapping.json",
//    "server/data/elasticsearch/entities_multi_field_search.json",
//    "server/data/elasticsearch/messages_mapping.json",
//    "server/data/elasticsearch/messages_multi_field_search.json",
//    "server/data/entity.js",
//    "server/data/favorite.js",
//    "server/data/feedback.js",
//    "server/data/follow.js",
//    "server/data/history.js",
//    "server/data/identifier.js",
//    "server/data/index.js",
//    "server/data/integration.js",
//    "server/data/invite.js",
//    "server/data/like.js",
//    "server/data/loading.js",
//    "server/data/message.js",
//    "server/data/mission/project.group.js",
//    "server/data/mission/project.js",
//    "server/data/mission/project.task.js",
//    "server/data/mobile.js",
//    "server/data/model/activity.js",
//    "server/data/model/apply.js",
//    "server/data/model/authorization.js",
//    "server/data/model/calendar/calendar.event.instance.js",
//    "server/data/model/calendar/calendar.event.js",
//    "server/data/model/calendar/calendar.js",
//    "server/data/model/calendar/calendar.shared.js",
//    "server/data/model/calendar/index.js",
//    "server/data/model/call_addition.js",
//    "server/data/model/call_duration.js",
//    "server/data/model/call_record.js",
//    "server/data/model/call_status.js",
//    "server/data/model/channel.js",
//    "server/data/model/client_number.js",
//    "server/data/model/comment.js",
//    "server/data/model/department.js",
//    "server/data/model/domain.js",
//    "server/data/model/drive.js",
//    "server/data/model/entities/article.js",
//    "server/data/model/entities/audio.js",
//    "server/data/model/entities/checklist.js",
//    "server/data/model/entities/device.js",
//    "server/data/model/entities/event.js",
//    "server/data/model/entities/file.js",
//    "server/data/model/entities/index.js",
//    "server/data/model/entities/issue.js",
//    "server/data/model/entities/mail.js",
//    "server/data/model/entities/note.js",
//    "server/data/model/entities/page.js",
//    "server/data/model/entities/place.js",
//    "server/data/model/entities/post.js",
//    "server/data/model/entities/process.js",
//    "server/data/model/entities/product.js",
//    "server/data/model/entities/question.js",
//    "server/data/model/entities/review.js",
//    "server/data/model/entities/snippet.js",
//    "server/data/model/entities/table.js",
//    "server/data/model/entities/video.js",
//    "server/data/model/entities/voice.js",
//    "server/data/model/entities/vote.js",
//    "server/data/model/entity.js",
//    "server/data/model/favorite.js",
//    "server/data/model/feedback.js",
//    "server/data/model/follow.js",
//    "server/data/model/history.js",
//    "server/data/model/identifier.js",
//    "server/data/model/index.js",
//    "server/data/model/integration.js",
//    "server/data/model/invite.js",
//    "server/data/model/like.js",
//    "server/data/model/loading.js",
//    "server/data/model/message.js",
//    "server/data/model/mission/index.js",
//    "server/data/model/mission/project.group.js",
//    "server/data/model/mission/project.js",
//    "server/data/model/mission/project.shared.js",
//    "server/data/model/mission/project.task.js",
//    "server/data/model/pinned.js",
//    "server/data/model/preference.js",
//    "server/data/model/profile.js",
//    "server/data/model/reminder.js",
//    "server/data/model/reminder.shared.js",
//    "server/data/model/reply.js",
//    "server/data/model/report.js",
//    "server/data/model/reserved_name.js",
//    "server/data/model/resource.js",
//    "server/data/model/schedule.js",
//    "server/data/model/securitylog.js",
//    "server/data/model/service.js",
//    "server/data/model/services/apicloud.js",
//    "server/data/model/services/appstore.js",
//    "server/data/model/services/asana.js",
//    "server/data/model/services/basecamp.js",
//    "server/data/model/services/box.js",
//    "server/data/model/services/command.js",
//    "server/data/model/services/custombot.js",
//    "server/data/model/services/evernote.js",
//    "server/data/model/services/flurry.js",
//    "server/data/model/services/github.js",
//    "server/data/model/services/inbound.js",
//    "server/data/model/services/inbox.js",
//    "server/data/model/services/index.js",
//    "server/data/model/services/jobdeer.js",
//    "server/data/model/services/mindstore.js",
//    "server/data/model/services/nextkr.js",
//    "server/data/model/services/onedrive.js",
//    "server/data/model/services/onenote.js",
//    "server/data/model/services/outbound.js",
//    "server/data/model/services/plugin.js",
//    "server/data/model/services/processon.js",
//    "server/data/model/services/quip.js",
//    "server/data/model/services/rss.js",
//    "server/data/model/services/sendcloud.js",
//    "server/data/model/services/shimo.js",
//    "server/data/model/services/slash.js",
//    "server/data/model/services/sqs.js",
//    "server/data/model/services/teambition.js",
//    "server/data/model/services/teamwork.js",
//    "server/data/model/services/trello.js",
//    "server/data/model/services/tuling.js",
//    "server/data/model/services/umeng.js",
//    "server/data/model/services/weibo.js",
//    "server/data/model/services/weixin.js",
//    "server/data/model/services/wooyun.js",
//    "server/data/model/services/worktile.js",
//    "server/data/model/services/worktiler.js",
//    "server/data/model/services/wunderlist.js",
//    "server/data/model/services/yangcong.js",
//    "server/data/model/services/yinxiang.js",
//    "server/data/model/services/youdaonote.js",
//    "server/data/model/services/zuimeia.js",
//    "server/data/model/session.js",
//    "server/data/model/sharedlink.js",
//    "server/data/model/statistic.js",
//    "server/data/model/tag.js",
//    "server/data/model/task/project.js",
//    "server/data/model/task/project_group.js",
//    "server/data/model/task/task.js",
//    "server/data/model/task/task_tag.js",
//    "server/data/model/team.js",
//    "server/data/model/unread.js",
//    "server/data/model/user.js",
//    "server/data/model/version.js",
//    "server/data/model/work_report.js",
//    "server/data/pinned.js",
//    "server/data/preference.js",
//    "server/data/profile.js",
//    "server/data/reminder.js",
//    "server/data/reply.js",
//    "server/data/report.js",
//    "server/data/reserved_name.js",
//    "server/data/resource.js",
//    "server/data/schedule.js",
//    "server/data/securitylog.js",
//    "server/data/service.js",
//    "server/data/session.js",
//    "server/data/sharedlink.js",
//    "server/data/source/init.js",
//    "server/data/source/integrations.js",
//    "server/data/source/user.js",
//    "server/data/statistic.js",
//    "server/data/tag.js",
//    "server/data/team.js",
//    "server/data/unread.js",
//    "server/data/user.js",
//    "server/data/version.js",
//    "server/data/work_report.js",
//    "server/devops/es-sync.js",
//    "server/devops/integrations-init.js",
//    "server/domain/apply.js",
//    "server/domain/authorization.js",
//    "server/domain/autoReply/entity.js",
//    "server/domain/autoReply/index.js",
//    "server/domain/autoReply/thirdplugin.js",
//    "server/domain/automation/base.js",
//    "server/domain/automation/calendar.js",
//    "server/domain/automation/chat.js",
//    "server/domain/automation/drive.js",
//    "server/domain/automation/index.js",
//    "server/domain/automation/manual.js",
//    "server/domain/automation/project.js",
//    "server/domain/base.js",
//    "server/domain/calendar.js",
//    "server/domain/call.js",
//    "server/domain/channel.js",
//    "server/domain/department.js",
//    "server/domain/drive.js",
//    "server/domain/entity.js",
//    "server/domain/favorite.js",
//    "server/domain/feed/base.js",
//    "server/domain/feed/channel.js",
//    "server/domain/feed/entity.js",
//    "server/domain/feed/index.js",
//    "server/domain/feed/message.js",
//    "server/domain/feed/project.js",
//    "server/domain/feed/team.js",
//    "server/domain/feed/user.js",
//    "server/domain/feedback.js",
//    "server/domain/follow.js",
//    "server/domain/general.js",
//    "server/domain/index.js",
//    "server/domain/integration.js",
//    "server/domain/mailer/index.js",
//    "server/domain/message.js",
//    "server/domain/mission.js",
//    "server/domain/pinned.js",
//    "server/domain/preference.js",
//    "server/domain/resource.js",
//    "server/domain/securityCode.js",
//    "server/domain/session.js",
//    "server/domain/sharedlink.component/calendar.js",
//    "server/domain/sharedlink.component/file.js",
//    "server/domain/sharedlink.component/folder.js",
//    "server/domain/sharedlink.component/index.js",
//    "server/domain/sharedlink.component/instance.js",
//    "server/domain/sharedlink.component/project.js",
//    "server/domain/sharedlink.component/task.js",
//    "server/domain/sharedlink.js",
//    "server/domain/sms/index.js",
//    "server/domain/team.js",
//    "server/domain/thirdpart.plugin/asana.js",
//    "server/domain/thirdpart.plugin/basecamp.js",
//    "server/domain/thirdpart.plugin/box.js",
//    "server/domain/thirdpart.plugin/evernote.js",
//    "server/domain/thirdpart.plugin/github.js",
//    "server/domain/thirdpart.plugin/index.js",
//    "server/domain/thirdpart.plugin/onedrive.js",
//    "server/domain/thirdpart.plugin/onenote.js",
//    "server/domain/thirdpart.plugin/plugin.js",
//    "server/domain/thirdpart.plugin/processon.js",
//    "server/domain/thirdpart.plugin/quip.js",
//    "server/domain/thirdpart.plugin/shimo.js",
//    "server/domain/thirdpart.plugin/teambition.js",
//    "server/domain/thirdpart.plugin/teamwork.js",
//    "server/domain/thirdpart.plugin/trello.js",
//    "server/domain/thirdpart.plugin/umeng.js",
//    "server/domain/thirdpart.plugin/weibo.js",
//    "server/domain/thirdpart.plugin/weixin.js",
//    "server/domain/thirdpart.plugin/worktile.js",
//    "server/domain/thirdpart.plugin/worktiler.js",
//    "server/domain/thirdpart.plugin/wunderlist.js",
//    "server/domain/thirdpart.plugin/yangcong.js",
//    "server/domain/thirdpart.plugin/yinxiang.js",
//    "server/domain/thirdpart.plugin/youdaonote.js",
//    "server/domain/user.js",
//    "server/domain/work_report.js",
//    "server/fetch/apicloud.js",
//    "server/fetch/appstore.js",
//    "server/fetch/asana.js",
//    "server/fetch/basecamp.js",
//    "server/fetch/call_duration.js",
//    "server/fetch/call_monitor.js",
//    "server/fetch/crawler_base.js",
//    "server/fetch/crawler_service_call.js",
//    "server/fetch/crawler_service_mail-sx.js",
//    "server/fetch/crawler_service_mail.js",
//    "server/fetch/crawler_service_other.js",
//    "server/fetch/crawler_service_reminder.js",
//    "server/fetch/crawler_service_schedule.js",
//    "server/fetch/crawler_service_unstable.js",
//    "server/fetch/flurry.js",
//    "server/fetch/inbox-sx.js",
//    "server/fetch/inbox-sxcp.js",
//    "server/fetch/inbox.js",
//    "server/fetch/index.js",
//    "server/fetch/jobdeer.js",
//    "server/fetch/mindstore.js",
//    "server/fetch/nextkr.js",
//    "server/fetch/reminder.js",
//    "server/fetch/reminder.notifier.js",
//    "server/fetch/reminder.notifier.message.js",
//    "server/fetch/reminder.servant.js",
//    "server/fetch/reminder.source.calendar.js",
//    "server/fetch/reminder.source.incubator.js",
//    "server/fetch/reminder.source.js",
//    "server/fetch/reminder.source.project.js",
//    "server/fetch/rsscrawler.js",
//    "server/fetch/schedule_message.js",
//    "server/fetch/sendcloud.js",
//    "server/fetch/umeng_app.js",
//    "server/fetch/umeng_feedback.js",
//    "server/fetch/weibocrawler.js",
//    "server/fetch/wooyun.js",
//    "server/handler.js",
//    "server/hooks/callback/index.js",
//    "server/hooks/callback/mobile.js",
//    "server/hooks/common/base.js",
//    "server/hooks/common/bot.js",
//    "server/hooks/common/index.js",
//    "server/hooks/common/internal.js",
//    "server/hooks/common/ping.js",
//    "server/hooks/incoming/amazonsns.js",
//    "server/hooks/incoming/appsignal.js",
//    "server/hooks/incoming/backlogtool.js",
//    "server/hooks/incoming/base.js",
//    "server/hooks/incoming/beanstalk.js",
//    "server/hooks/incoming/beecloud.js",
//    "server/hooks/incoming/bitbucket.js",
//    "server/hooks/incoming/bughd.js",
//    "server/hooks/incoming/bugsnag.js",
//    "server/hooks/incoming/buildkite.js",
//    "server/hooks/incoming/circleci.js",
//    "server/hooks/incoming/cloud66.js",
//    "server/hooks/incoming/codeship.js",
//    "server/hooks/incoming/codingnet.js",
//    "server/hooks/incoming/csdncode.js",
//    "server/hooks/incoming/custombot.js",
//    "server/hooks/incoming/daike.js",
//    "server/hooks/incoming/desk.js",
//    "server/hooks/incoming/errorception.js",
//    "server/hooks/incoming/firim.js",
//    "server/hooks/incoming/general.js",
//    "server/hooks/incoming/git.js",
//    "server/hooks/incoming/gitcafe.js",
//    "server/hooks/incoming/github.js",
//    "server/hooks/incoming/gitlab.js",
//    "server/hooks/incoming/gitlabci.js",
//    "server/hooks/incoming/gogs.js",
//    "server/hooks/incoming/helpscout.js",
//    "server/hooks/incoming/heroku.js",
//    "server/hooks/incoming/hockeyapp.js",
//    "server/hooks/incoming/honeybadger.js",
//    "server/hooks/incoming/index.js",
//    "server/hooks/incoming/intercom.js",
//    "server/hooks/incoming/jenkins.js",
//    "server/hooks/incoming/jiankongbao.js",
//    "server/hooks/incoming/jinshuju.js",
//    "server/hooks/incoming/jira.js",
//    "server/hooks/incoming/jobtong.js",
//    "server/hooks/incoming/logentries.js",
//    "server/hooks/incoming/magnumci.js",
//    "server/hooks/incoming/mail.js",
//    "server/hooks/incoming/mailgun.js",
//    "server/hooks/incoming/mikecrm.js",
//    "server/hooks/incoming/newrelic.js",
//    "server/hooks/incoming/opsgenie.js",
//    "server/hooks/incoming/oschina.js",
//    "server/hooks/incoming/pagerduty.js",
//    "server/hooks/incoming/papertrail.js",
//    "server/hooks/incoming/pgyer.js",
//    "server/hooks/incoming/pingpp.js",
//    "server/hooks/incoming/pivotaltracker.js",
//    "server/hooks/incoming/qingcloud.js",
//    "server/hooks/incoming/raygun.js",
//    "server/hooks/incoming/remotebot.js",
//    "server/hooks/incoming/runscope.js",
//    "server/hooks/incoming/segment.js",
//    "server/hooks/incoming/semaphore.js",
//    "server/hooks/incoming/sendcloud.js",
//    "server/hooks/incoming/sentry.js",
//    "server/hooks/incoming/serverdensity.js",
//    "server/hooks/incoming/stash.js",
//    "server/hooks/incoming/stripe.js",
//    "server/hooks/incoming/svn.js",
//    "server/hooks/incoming/swathub.js",
//    "server/hooks/incoming/teambition.js",
//    "server/hooks/incoming/teamcity.js",
//    "server/hooks/incoming/teamwork.js",
//    "server/hooks/incoming/tower.js",
//    "server/hooks/incoming/travisci.js",
//    "server/hooks/incoming/trello.js",
//    "server/hooks/incoming/uptimerobot.js",
//    "server/hooks/incoming/uservoice.js",
//    "server/hooks/incoming/vsonline.js",
//    "server/hooks/incoming/weixin.js",
//    "server/hooks/incoming/wiznote.js",
//    "server/hooks/incoming/wordpress.js",
//    "server/hooks/incoming/worktile.js",
//    "server/hooks/incoming/worktiler.js",
//    "server/hooks/incoming/wunderlist.js",
//    "server/hooks/incoming/zendesk.js",
//    "server/hooks/incoming/zuimei.js",
//    "server/hooks/index.js",
//    "server/hooks/validator.js",
//    "server/lib/node-poplib.js",
//    "server/lib/ucpaas/index.js",
//    "server/lib/yuntongxun/index.js",
//    "server/permission/base.js",
//    "server/permission/calendar.js",
//    "server/permission/channel.js",
//    "server/permission/comment.js",
//    "server/permission/core.js",
//    "server/permission/drive.js",
//    "server/permission/entity.js",
//    "server/permission/index.js",
//    "server/permission/message.js",
//    "server/permission/mission.js",
//    "server/permission/service.js",
//    "server/permission/serviceAuth.js",
//    "server/permission/session.js",
//    "server/permission/sharedlink.js",
//    "server/permission/team.js",
//    "server/permission/teamSite.js",
//    "server/permission/user.js",
//    "server/permission/work_report.js",
//    "server/route/calendar.js",
//    "server/route/drive.js",
//    "server/route/index.js",
//    "server/route/mission.js",
//    "server/route/report.js",
//    "server/route/route.old.js",
//    "server/route.hook.js",
//    "server/statistic/index.js"
];

var prefix = '/Users/huangling/wanghao/tmp/lcweb/';

var files_final = [];

files.forEach(function(file) {
    files_final.push(prefix + file);
});

module.exports = files_final;
